#if !canImport(ObjectiveC)
import XCTest

extension ProcessStartTimeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ProcessStartTimeTests = [
        ("testStartTime", testStartTime),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ProcessStartTimeTests.__allTests__ProcessStartTimeTests),
    ]
}
#endif
